services:
  - type: web
    name: visual-arts-portal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromContext: parameter
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8000
